import React, { useState, useEffect } from 'react';
import { ListTodo, Trash2, Search, X, Loader2, AlertCircle, Sun, Moon } from 'lucide-react';
import { taskApi, isOverdue } from './api/taskApi';
import DashboardStats from './components/DashboardStats';
import TaskCard from './components/TaskCard';
import TaskForm from './components/TaskForm';

export default function App() {
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [filter, setFilter] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [editingTask, setEditingTask] = useState(null);
  const [toasts, setToasts] = useState([]);
  
  // Theme state: defaults to dark mode
  const [theme, setTheme] = useState(() => localStorage.getItem('theme') || 'dark');

  // Sync theme to body class list and localStorage
  useEffect(() => {
    if (theme === 'light') {
      document.body.classList.add('light-mode');
    } else {
      document.body.classList.remove('light-mode');
    }
    localStorage.setItem('theme', theme);
  }, [theme]);

  // Toast helper
  const addToast = (message, type = 'success') => {
    const id = Date.now();
    setToasts((prev) => [...prev, { id, message, type }]);
    setTimeout(() => {
      setToasts((prev) => prev.filter((t) => t.id !== id));
    }, 4000);
  };

  // Fetch tasks
  const loadTasks = async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await taskApi.getAllTasks();
      setTasks(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error(err);
      setError('Could not connect to backend server. Ensure Spring Boot is running on http://localhost:8080.');
      addToast('Backend connection failed', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadTasks();
  }, []);

  // Create or Update task
  const handleSubmitTask = async (taskData) => {
    try {
      const isEdit = !!editingTask;
      let saved;

      if (isEdit) {
        saved = await taskApi.updateTask(editingTask.id, taskData);
        addToast(`Task "${saved.tName}" updated successfully`);
      } else {
        // Since ID is not auto-generated by the database, calculate the next unique ID on the client
        const nextId = tasks.length > 0 ? Math.max(...tasks.map(t => t.id)) + 1 : 1;
        const taskWithId = {
          ...taskData,
          id: nextId
        };
        saved = await taskApi.addTask(taskWithId);
        addToast(`Task "${saved.tName}" created successfully`);
      }

      setEditingTask(null);
      loadTasks();
    } catch (err) {
      console.error(err);
      addToast('Failed to save task', 'error');
    }
  };

  // Toggle complete state
  const handleToggleComplete = async (task) => {
    try {
      const isCompleted = task.completeStatus || !!task.completedAt;
      let updated;

      if (!isCompleted) {
        // Mark complete: use status endpoint (PUT /{id}/status)
        updated = await taskApi.completeTask(task.id);
        addToast(`Completed "${updated.tName}"`);
      } else {
        // Mark active: use normal update endpoint (PUT /{id}) with reset fields
        const resetTask = {
          ...task,
          completeStatus: false,
          completedAt: null
        };
        updated = await taskApi.updateTask(task.id, resetTask);
        addToast(`Marked "${updated.tName}" as active`);
      }
      loadTasks();
    } catch (err) {
      console.error(err);
      addToast('Failed to toggle completion status', 'error');
    }
  };

  // Delete task
  const handleDeleteTask = async (id) => {
    if (!window.confirm('Are you sure you want to delete this task?')) return;
    try {
      await taskApi.deleteTask(id);
      addToast('Task deleted successfully');
      if (editingTask && editingTask.id === id) {
        setEditingTask(null);
      }
      loadTasks();
    } catch (err) {
      console.error(err);
      addToast('Failed to delete task', 'error');
    }
  };

  // Clear all tasks
  const handleClearAll = async () => {
    if (!window.confirm('Are you sure you want to delete all tasks? This cannot be undone.')) return;
    try {
      await taskApi.deleteAllTasks();
      addToast('All tasks cleared successfully');
      setEditingTask(null);
      loadTasks();
    } catch (err) {
      console.error(err);
      addToast('Failed to clear tasks', 'error');
    }
  };

  // Filter & Search tasks
  const processedTasks = tasks
    .filter((task) => {
      const name = (task.tName || '').toLowerCase();
      const desc = (task.tDescription || '').toLowerCase();
      const matchSearch = name.includes(searchQuery.toLowerCase()) || desc.includes(searchQuery.toLowerCase());

      if (!matchSearch) return false;

      if (filter === 'completed') return task.completeStatus || !!task.completedAt;
      if (filter === 'active') return !task.completeStatus && !task.completedAt;
      if (filter === 'overdue') return !task.completeStatus && !task.completedAt && isOverdue(task.dueAt);
      
      return true; // 'all'
    })
    .sort((a, b) => {
      // Sort logic: Overdue first, then active tasks, then completed tasks
      const aComp = a.completeStatus || !!a.completedAt;
      const bComp = b.completeStatus || !!b.completedAt;
      
      if (aComp !== bComp) return aComp ? 1 : -1;
      
      if (!aComp) {
        const aOver = isOverdue(a.dueAt);
        const bOver = isOverdue(b.dueAt);
        if (aOver !== bOver) return aOver ? -1 : 1;
      }
      
      return b.id - a.id;
    });

  return (
    <div className="app-container">
      {/* Toast Notifier */}
      <div className="toast-container">
        {toasts.map((toast) => (
          <div key={toast.id} className={`toast toast-${toast.type}`}>
            <span>{toast.message}</span>
          </div>
        ))}
      </div>

      {/* Main Header */}
      <header className="app-header">
        <div className="logo-section">
          <ListTodo className="logo-icon" />
          <h1 className="logo-text">TaskSphere</h1>
        </div>
        <div className="header-actions">
          {/* Light/Dark Theme Toggle */}
          <button 
            className="theme-toggle-btn"
            onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
            title={`Switch to ${theme === 'dark' ? 'Light' : 'Dark'} Mode`}
          >
            {theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}
          </button>
          
          <button className="btn btn-secondary" onClick={loadTasks} disabled={loading}>
            Refresh
          </button>
          {tasks.length > 0 && (
            <button className="btn btn-danger" onClick={handleClearAll}>
              <Trash2 size={16} /> Clear All
            </button>
          )}
        </div>
      </header>

      {/* Dashboard Stats */}
      <DashboardStats tasks={tasks} />

      {/* Grid Layout */}
      <div className="dashboard-grid">
        {/* Sidebar Form */}
        <aside>
          <TaskForm 
            onSubmit={handleSubmitTask} 
            editingTask={editingTask} 
            onCancelEdit={() => setEditingTask(null)} 
          />
        </aside>

        {/* Tasks View Section */}
        <main className="tasks-section">
          {/* Filters and Search Bar */}
          <div className="filter-bar">
            <div className="filter-tabs">
              {['all', 'active', 'completed', 'overdue'].map((tab) => (
                <button
                  key={tab}
                  className={`filter-tab ${filter === tab ? 'active' : ''}`}
                  onClick={() => setFilter(tab)}
                >
                  {tab.charAt(0).toUpperCase() + tab.slice(1)}
                </button>
              ))}
            </div>

            <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
              <input
                type="text"
                placeholder="Search tasks..."
                className="form-input"
                style={{ paddingLeft: '2.5rem', width: '220px', background: 'var(--panel-bg)' }}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
              <Search 
                size={16} 
                style={{ position: 'absolute', left: '1rem', color: 'var(--color-text-dim)' }} 
              />
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery('')}
                  style={{
                    position: 'absolute',
                    right: '0.75rem',
                    background: 'transparent',
                    border: 'none',
                    color: 'var(--color-text-muted)',
                    cursor: 'pointer',
                  }}
                >
                  <X size={14} />
                </button>
              )}
            </div>
          </div>

          {/* List States */}
          {loading ? (
            <div className="empty-state">
              <Loader2 className="empty-icon" style={{ animation: 'spin 1.5s linear infinite' }} />
              <p className="empty-title">Loading Tasks...</p>
              <style>{`
                @keyframes spin {
                  from { transform: rotate(0deg); }
                  to { transform: rotate(360deg); }
                }
              `}</style>
            </div>
          ) : error ? (
            <div className="glass-panel" style={{ padding: '2rem', display: 'flex', gap: '1.25rem', borderColor: 'var(--color-danger)', background: 'var(--color-danger-light)' }}>
              <AlertCircle size={28} style={{ color: 'var(--color-danger)', flexShrink: 0 }} />
              <div>
                <h3 style={{ fontSize: '1.1rem', marginBottom: '0.5rem' }}>Connection Error</h3>
                <p style={{ fontSize: '0.9rem', color: 'var(--color-text-muted)', lineHeight: '1.4' }}>{error}</p>
                <button className="btn btn-secondary" style={{ marginTop: '1rem', fontSize: '0.8rem', padding: '0.5rem 1rem' }} onClick={loadTasks}>
                  Retry Connection
                </button>
              </div>
            </div>
          ) : processedTasks.length === 0 ? (
            <div className="glass-panel empty-state">
              <ListTodo className="empty-icon" />
              <h3 className="empty-title">No tasks found</h3>
              <p className="empty-subtitle">
                {searchQuery || filter !== 'all' 
                  ? 'Try modifying your search query or filter tabs.'
                  : 'Start by filling in the details in the sidebar to create your first task!'}
              </p>
            </div>
          ) : (
            <div className="tasks-list">
              {processedTasks.map((task) => (
                <TaskCard
                  key={task.id}
                  task={task}
                  onToggleComplete={handleToggleComplete}
                  onDelete={handleDeleteTask}
                  onEdit={setEditingTask}
                />
              ))}
            </div>
          )}
        </main>
      </div>
    </div>
  );
}
